image: node:10

stages:
  - install
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1h 
    paths:
      - node_modules/
  only:
    - master


build:
    stage: build
    variables:
        BUILD_CONFIG: 'production'
    dependencies:
        - install
    script:
      - npm run build --prod
    artifacts:
        expire_in: 1h 
        paths:
          - dist/
    only:
        - master