
image: node:10:16.0

stages:
    - install
    - build
    - deploy

install:
    stages: install
    script:
        - npm install
    artifacts:
        expire_in: 1h 
        paths:
            - node_modules/
        cache:
            paths:
                - node_modules/